### ISSUE TITLE
Error in loading Webparts for guest user

### ISSUE THREAD

**Issue by SnappyFPV** [microsoft-search/pnp-modern-search#127]
**Version used**
Ex: 3.10

**Describe the bug**
Webparts couldn't loaded when i access the site as guest user. 
No CDN is enabled in the tenant.

Error Message:

[SPLoaderError.loadComponentError]:
Failed to load component "096b96cc-8a44-41fa-9b4d-c0ab2ab2a779" (SearchBoxWebPart). Original error: Failed to load path dependency "SearchBoxWebPartStrings" from component "096b96cc-8a44-41fa-9b4d-c0ab2ab2a779" (SearchBoxWebPart). Original error: Script error for: 096b96cc-8a44-41fa-9b4d-c0ab2ab2a779_3.10.0/SearchBoxWebPartStrings
http://requirejs.org/docs/errors.html#scripterror

INNERERROR:
Failed to load path dependency "SearchBoxWebPartStrings" from component "096b96cc-8a44-41fa-9b4d-c0ab2ab2a779" (SearchBoxWebPart). Original error: Script error for: 096b96cc-8a44-41fa-9b4d-c0ab2ab2a779_3.10.0/SearchBoxWebPartStrings
http://requirejs.org/docs/errors.html#scripterror
CALLSTACK:
Error
at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_e7992ed501f0950c4dd86f6962d42e15.js:4:53271)
at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_e7992ed501f0950c4dd86f6962d42e15.js:20:10505)
at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_e7992ed501f0950c4dd86f6962d42e15.js:20:53017)
at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_e7992ed501f0950c4dd86f6962d42e15.js:20:49048)
at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_e7992ed501f0950c4dd86f6962d42e15.js:20:44589

**To Reproduce**
Access the site as invited guest user in the tenant.

**Comment by wobba** [comment]
You need to ensure your users have access to your app catalog. Not an issue per say on these web parts.

See https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/ for a good explanation.
