### ISSUE TITLE
Refiner Webpart showing no count during load and sometimes even after load

### ISSUE THREAD

**Issue by martinlingstuyl** [microsoft-search/pnp-modern-search#2788]
**Version used**
4.8

**Describe the bug**
When using the filter webpart, The item counters are not correctly updated in the following scenario:

When using a filter on a Managed Metadata column (that has been exposed through a RefinableString property) with template `Checkbox` and Multi values as `false`.

If I update Multi values to `true`, the webpart works as expected.

The error that occurs in the DevTools:

```text
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at t.<anonymous> (modern-search-filters-web-part_6d3e2ea683ed44382cd9.js:2:1362686)
    at modern-search-filters-web-part_6d3e2ea683ed44382cd9.js:2:1359727
    at Object.next (modern-search-filters-web-part_6d3e2ea683ed44382cd9.js:2:1359832)
    at o (modern-search-filters-web-part_6d3e2ea683ed44382cd9.js:2:1358573)
```
When following the error and finding it in the source code, it seems to come from here:
https://github.com/microsoft-search/pnp-modern-search/blob/cda9ca9fc0ccd3068f1b64ab8b68e2a5c9d4a516/search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx#L128

It seems to run into a nullreference exception when loading the Checkbox template or some such.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a library field based on Managed Metadata
2. Add some files and fill the metadata field
3. (Wait for search indexing operation)
4. Configure RefinableString properties to map to your fields: For example, RefinableString100 to ows_TestCol1
5. Update the library content to trigger re-indexing.
6. Create a page with a search result webpart and search filter webpart and connect them.
7. Configure the RefinableString properties in your filter with the Checbox template and Multivalues set to false.

**Expected behavior**
I'd expect the counter to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/5267487/220330240-8d0899c6-688b-4e5a-bb49-54f4c61f1ac0.png)

VS

![image](https://user-images.githubusercontent.com/5267487/220330155-c72af577-5be9-457f-b01c-6faa779ef0ab.png)

Setting this to true works, setting it to false breaks the counter.
![image](https://user-images.githubusercontent.com/5267487/220330434-036f7499-a79e-45df-8bdd-30bafae46d75.png)

**Desktop (please complete the following information):**
Edge
Windows 11

**Comment by martinlingstuyl** [comment]
Thanks for responding @kasperbolarsen! I'll look into it...

**Comment by martinlingstuyl** [comment]
Hi @kasperbolarsen, I can confirm that I cannot reproduce the problem in version 4.9. Awesome! 👏 I'll close this issue.
