### ISSUE TITLE
Intermittent errors : Number of search results 'undefined' with paging lost

### ISSUE THREAD

**Issue by ferrarirosso** [microsoft-search/pnp-modern-search#2821]
**Version used**
4.5.4

**Describe the bug**
We have rare cases where our users get a "undefined" result instead of the number of search results. 
After getting a screenshot of this, I did manage to reproduce this behaviour once :
1. undefined is shown instead of the number of search results
2. the paging component is gone => only the first page is shown, but there are more results for this query

![Screenshot 2023-03-05 at 08 53 12](https://user-images.githubusercontent.com/5904018/222948878-91470154-bca4-46bc-b83e-165a4e033cd6.png)

Our setup is :
- 4 search verticals
- 4 filters wp
- 4 results wp

Looking at the dev toolbar, I have found the following error messages :
`sp-pages-assembly_de_c2bfc39ce26869cdb8fe8d24b170c4b3.js:70 Uncaught (in promise) Error: Dynamic Data Source has not been initialized.
    at e._assertSourceExists (sp-pages-assembly_de_c2bfc39ce26869cdb8fe8d24b170c4b3.js:70:1019292)
    at e.notifyPropertyChanged (sp-pages-assembly_de_c2bfc39ce26869cdb8fe8d24b170c4b3.js:70:1014931)
    at ee.renderCompleted (modern-search-box-web-part_f0220a380781984185a5.js:1:197710)
    at ee.<anonymous> (modern-search-box-web-part_f0220a380781984185a5.js:1:197318)
    at Generator.next (<anonymous>)
    at s (modern-search-box-web-part_f0220a380781984185a5.js:1:195244)
`

I found some traces here [SPFx 1.7.0 Dynamic Data - Connections between components randomly 'lost' after a whole page refresh ](https://github.com/SharePoint/sp-dev-docs/issues/2985) maybe it's related 

**To Reproduce**
As explained above, difficult to reproduce.

**Comment by wobba** [comment]
We don't traige bugs on older versions. If you can repro with the latest version feel free to log a new issue.
