### ISSUE TITLE
Updating PnP Search Webparts from V4.5 to latest V4.8

### ISSUE THREAD

**Issue by SSkj2013** [microsoft-search/pnp-modern-search#2907]
I am trying to upgrade my webparts from V4.5 to 4.8. The name for both .sppkg files are the same. 
I removed the v4.5's webparts from all the pages where they have been added. Removed the v4.5's pnp-modern-search-parts-v4.sppkg, also from first and second stage recycle bins. 
Uploaded the new v4.8's pnp-modern-search-parts-v4.sppkg and published it. 
Went to a page and added the pnp search verticals webpart, it gives me the following error. I reverted back to V4.5 and this error goes away. What is correct method to upgrade between these two versions? I have not found any documentation.  Any help is greately appreciated. 

_Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Script error for: 544c1372-77ae-40a0-9095-805ae2a0d5e9_4.8.0/SearchVerticalsWebPartStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 544c1372-77ae-40a0-9095-805ae2a0d5e9_4.8.0/SearchVerticalsWebPartStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:1:1), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:1:1), <anonymous>:30:244)
<img width="496" alt="image" src="https://user-images.githubusercontent.com/95306710/231800150-de3223f5-5fa2-42dc-a50e-ef7a4b074d33.png">_

**Comment by SSkj2013** [comment]
Also I tried to upload v4.8 as a new version on top of existing v4.5, still has the same issue. 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/95306710/231802606-81471e24-d86d-4355-a117-80e042bb7bde.png">

**Comment by SSkj2013** [comment]
This issue can be marked closed. This was a cache issue, it is now resolved.
