### ISSUE TITLE
When pagination is done to Page 10 and above getting error related to Token renewal

### ISSUE THREAD

**Issue by mw-new-test** [microsoft-search/pnp-modern-search#3238]
**Version used**
Ex: 4.9.1

**Describe the bug**
On paginating search results in PnP Modern Search results webpart with total of 1000+ results showing pages in batches of 10, somewhere around 8th page or 9th page, we get the below errors.
On this page, it does not show any results and shows error Token request previously failed within the results webpart.

Unsafe attempt to initiate navigation for frame with origin 'https://test.sharepoint.com' from frame with URL 'https://login.microsoftonline.com/xxxxxxx-72ce-4192-aba4-xxxxxxxxxxx/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default%20openid%20profile&client_id=xxxxxxxx-0b3b-4cad-a0ae-xxxxxxxxxxx&redirect_uri=https%3A%2F%2Ftest.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&nonce=x&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.4.12&sid=xxxxxxx-1806-454b-8ae6-xxxxxxxxxxxx&client-request-id=xxxxxxx-4469-4f12-b112-xxxxxxxxxxxx&prompt=none&response_mode=fragment'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'https://login.microsoftonline.com/xxxxxxx-72ce-4192-aba4-xxxxxxxxxxxx/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default%20openid%20profile&client_id=21a90146-0b3b-4cad-a0ae-1ff07389317b&redirect_uri=https%3A%2F%2Ftest.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&nonce=xxxxxxxx-a7b6-40c4-ba32-xxxxxxxxxxxx&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.4.12&sid=xxxxxxx-1806-454b-8ae6-xxxxxxxxxxxx&client-request-id=xxxxxxx-4469-4f12-b112-xxxxxxxxxxxx&prompt=none&response_mode=fragment&iframe-request-id=xxxxxxxx-6353-47a6-99ab-xxxxxxxxxxxx'.

Uncaught (in promise) ClientAuthError: Token renewal operation failed due to timeout.
    at t [as constructor] (chunk.vendors~msalImplicit~msalImplicitLegacy_none_de38c503bf17cb27e220.js:1:8320)
    at new t (chunk.vendors~msalImplicit~msalImplicitLegacy_none_de38c503bf17cb27e220.js:1:8879)
    at t.createTokenRenewalTimeoutError (chunk.vendors~msalImplicit~msalImplicitLegacy_none_de38c503bf17cb27e220.js:1:9360)
    at chunk.vendors~msalImplicit~msalImplicitLegacy_none_de38c503bf17cb27e220.js:1:40879
	
Uncaught (in promise) Error: Token request previously failed
    at new t (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:1754)
    at e._getTokenInternal (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:3807)
    at e.getToken (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:2612)
    at sp-pages-assembly_en-gb_893c9a9a2a57f27753ec75917bc11f5c.js:78:165455
	
	modern-search-results-web-part_9f9fef015a0961ba9417.js

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Configure PnP Modern Search results webpart with Microsoft Search as data source 
2. Include External Content source for interleaved results (Files, List, Sites and External Item)
3. Setup Pagination to show 10 results per page
4. Search by entering a keyword
5. Keep clicking next page sequential from 1 to 2, 2 to 3, 3 to 4....
6. See error

**Expected behavior**
We should not see any error and based on the number of results showing throw "Show results count", it should allow to paginate as many pages based on the results count

**Screenshots**

**Desktop (please complete the following information):**
 - Edge, Chrome

**Additional context**

**Comment by wobba** [comment]
I suggest you replicate your queries in the Graph Explorer as this likely is an API issue, and then log the issue on the API accordingly. If the same queries work in the explorer, then we have to compare what the web part request looks like to check for any potential issues.

As long as you follow the guide at https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0#page-search-results you should be ok. Remember that the total amount of results is an estimation, not accurate.

**Comment by mw-new-test** [comment]
> I suggest you replicate your queries in the Graph Explorer as this likely is an API issue, and then log the issue on the API accordingly. If the same queries work in the explorer, then we have to compare what the web part request looks like to check for any potential issues.
> 
> As long as you follow the guide at https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0#page-search-results you should be ok. Remember that the total amount of results is an estimation, not accurate.

We did the same test with Graph API incrementing pages sequentially but did not get any issue. It worked correctly with Graph  and we tested up until 20 pages i.e. 200 results.

**Comment by wobba** [comment]
@mw-new-test your next step is then comparing the request made by the web part with what you tested in the graph explorer. Feel free to share samples and differences you see.

**Comment by mw-new-test** [comment]
I keep running into this issue only on PnP Modern Search.
I have more than 100,000 items in results and when I paginate, somewhere around Page 20+, I get response -**"apiVersion":"2.0"** instead of actual 10 results that are supposed to be on the Page.

I tried replicating issue with Graph API but was not successful. Even after page 20, Graph API returned SP and external results. Infact, I went as far as 34 pages and did not get an issue.

This time around, I did not get any access token related issues. 
"size\":10,\"from\":220 --> This request returned correct results (Page 23)
"size\":10,\"from\":230 --> This failed although showed status 200, it did not return the results (Page 24)

Below is the request and response I saw from Developer tools from PnP Modern Search.
    "request": {
          "method": "POST",
          "url": "https://graph.microsoft.com/v1.0/search/query",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Authorization",
              "value": "Bearer abc"
            },
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 3471,
          "bodySize": 2146,
          "postData": {
            "mimeType": "application/json",
            "text": "{\"requests\":[{\"entityTypes\":[\"driveItem\",\"externalItem\",\"listItem\",\"site\"],\"query\":{\"queryString\":\"(* AND NOT(FileType:html OR FileType:css OR FileType:xml OR FileType:js OR FileType:sppkg))\",\"queryTemplate\":\"(* AND NOT(FileType:html OR FileType:css OR FileType:xml OR FileType:js OR FileType:sppkg)) \"},\"size\":10,\"from\":230,\"fields\":[\"Authors\",\"contentTypeId\",\"createdBy\",\"CreatedByName\",\"createdDateTime\",\"CreatedOn\",\"department\",\"description\",\"displayName\",\"end\",\"ExternalPath\",\"filetype\",\"FileType\",\"folder\",\"from\",\"givenName\",\"Id\",\"lastModifiedBy\",\"lastModifiedDateTime\",\"LastModifiedTime\",\"modifiedBy\",\"name\",\"objectName\",\"owsmetadatafacetinfo\",\"PageTree\",\"parentReference\",\"phones\",\"productMDMBU\",\"productMDMDescription\",\"productMDMFunctionalArea\",\"productMDMName\",\"productMDMProductLine\",\"RefinableString110\",\"replyTo\",\"sender\",\"size\",\"Source\",\"SpaceName\",\"SpaceType\",\"start\",\"subject\",\"surname\",\"title\",\"Type\",\"UpdatedByName\",\"UpdatedOn\",\"url\",\"userPrincipalName\",\"webUrl\",\"driveType\",\"contentType\",\"learningObjectId\",\"ParentLink\",\"documentLink\",\"owstaxidmetadataalltagsinfo\"],\"aggregations\":[{\"field\":\"FileType\",\"bucketDefinition\":{\"isDescending\":false,\"minimumCount\":1,\"sortBy\":\"keyAsString\"},\"size\":\"9999\"},{\"field\":\"ModifiedBy\",\"bucketDefinition\":{\"isDescending\":false,\"minimumCount\":1,\"sortBy\":\"keyAsString\"},\"size\":\"20000\"},{\"field\":\"RefinableString110\",\"bucketDefinition\":{\"isDescending\":false,\"minimumCount\":1,\"sortBy\":\"keyAsString\"},\"size\":\"20000\"},{\"field\":\"LastModifiedTime\",\"bucketDefinition\":{\"isDescending\":false,\"minimumCount\":1,\"sortBy\":\"keyAsString\",\"ranges\":[{\"to\":\"2022-10-05T11:04:05.412Z\"},{\"from\":\"2022-10-05T11:04:05.412Z\",\"to\":\"2023-07-05T11:04:05.412Z\"},{\"from\":\"2023-07-05T11:04:05.412Z\",\"to\":\"2023-09-05T11:04:05.412Z\"},{\"from\":\"2023-09-05T11:04:05.412Z\",\"to\":\"2023-09-28T11:04:05.412Z\"},{\"from\":\"2023-09-28T11:04:05.412Z\",\"to\":\"2023-10-04T11:04:05.412Z\"},{\"from\":\"2023-10-04T11:04:05.412Z\",\"to\":\"2023-10-05T11:05:05.412Z\"},{\"from\":\"2023-10-05T11:05:05.412Z\"}]},\"size\":10}],\"contentSources\":[\"/external/connections/confluence1\"],\"queryAlterationOptions\":{\"enableModification\":false,\"enableSuggestion\":false}}]}"
          }
        },
      "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "cookies": [],
          "content": {
            "size": 20,
            "mimeType": "application/json",
            "compression": -37,
            **"text": "{\"apiVersion\":\"2.0\"}"**
          },
          "redirectURL": "",
          "headersSize": 689,
          "bodySize": 57,
          "_transferSize": 746,
          "_error": null
        },

**Comment by wobba** [comment]
Can you compare the json requests you make in the explorer vs what is made via the web parts? To figure out what part of the request makes it behave different.

**Comment by mw-new-test** [comment]
Below is the Graph API request which returns me correct response meaning 10 results on the page

POST https://graph.microsoft.com/v1.0/search/query

POST /v1.0/search/query HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxxxxxx
 
{
"requests": [
{
"entityTypes": ["driveItem", "externalItem", "listItem", "site"],
"contentSources": [
"/external/connections/confluence1"
],
"query": {
"queryString": "*"
},
"from": 230,
"size": 10
}
]
}
 
HTTP/1.1 200 OK

**Comment by wobba** [comment]
This is the request the web part is doing from what you pasted.

```json
{
    "requests": [
        {
            "entityTypes": [
                "driveItem",
                "externalItem",
                "listItem",
                "site"
            ],
            "query": {
                "queryString": "(* AND NOT(FileType:html OR FileType:css OR FileType:xml OR FileType:js OR FileType:sppkg))",
                "queryTemplate": "(* AND NOT(FileType:html OR FileType:css OR FileType:xml OR FileType:js OR FileType:sppkg)) "
            },
            "size": 10,
            "from": 230,
            "fields": [
                "Authors",
                "contentTypeId",
                "createdBy",
                "CreatedByName",
                "createdDateTime",
                "CreatedOn",
                "department",
                "description",
                "displayName",
                "end",
                "ExternalPath",
                "filetype",
                "FileType",
                "folder",
                "from",
                "givenName",
                "Id",
                "lastModifiedBy",
                "lastModifiedDateTime",
                "LastModifiedTime",
                "modifiedBy",
                "name",
                "objectName",
                "owsmetadatafacetinfo",
                "PageTree",
                "parentReference",
                "phones",
                "productMDMBU",
                "productMDMDescription",
                "productMDMFunctionalArea",
                "productMDMName",
                "productMDMProductLine",
                "RefinableString110",
                "replyTo",
                "sender",
                "size",
                "Source",
                "SpaceName",
                "SpaceType",
                "start",
                "subject",
                "surname",
                "title",
                "Type",
                "UpdatedByName",
                "UpdatedOn",
                "url",
                "userPrincipalName",
                "webUrl",
                "driveType",
                "contentType",
                "learningObjectId",
                "ParentLink",
                "documentLink",
                "owstaxidmetadataalltagsinfo"
            ],
            "aggregations": [
                {
                    "field": "FileType",
                    "bucketDefinition": {
                        "isDescending": false,
                        "minimumCount": 1,
                        "sortBy": "keyAsString"
                    },
                    "size": "9999"
                },
                {
                    "field": "ModifiedBy",
                    "bucketDefinition": {
                        "isDescending": false,
                        "minimumCount": 1,
                        "sortBy": "keyAsString"
                    },
                    "size": "20000"
                },
                {
                    "field": "RefinableString110",
                    "bucketDefinition": {
                        "isDescending": false,
                        "minimumCount": 1,
                        "sortBy": "keyAsString"
                    },
                    "size": "20000"
                },
                {
                    "field": "LastModifiedTime",
                    "bucketDefinition": {
                        "isDescending": false,
                        "minimumCount": 1,
                        "sortBy": "keyAsString",
                        "ranges": [
                            {
                                "to": "2022-10-05T11:04:05.412Z"
                            },
                            {
                                "from": "2022-10-05T11:04:05.412Z",
                                "to": "2023-07-05T11:04:05.412Z"
                            },
                            {
                                "from": "2023-07-05T11:04:05.412Z",
                                "to": "2023-09-05T11:04:05.412Z"
                            },
                            {
                                "from": "2023-09-05T11:04:05.412Z",
                                "to": "2023-09-28T11:04:05.412Z"
                            },
                            {
                                "from": "2023-09-28T11:04:05.412Z",
                                "to": "2023-10-04T11:04:05.412Z"
                            },
                            {
                                "from": "2023-10-04T11:04:05.412Z",
                                "to": "2023-10-05T11:05:05.412Z"
                            },
                            {
                                "from": "2023-10-05T11:05:05.412Z"
                            }
                        ]
                    },
                    "size": 10
                }
            ],
            "contentSources": [
                "/external/connections/confluence1"
            ],
            "queryAlterationOptions": {
                "enableModification": false,
                "enableSuggestion": false
            }
        }
    ]
}
```

**Comment by mw-new-test** [comment]
It was a bug with Graph API that Microsoft was able to replicate and a fix is being rolled out. This issue can be closed
