### ISSUE TITLE
Error AADSTS65001 only on vertical web part

### ISSUE THREAD

**Issue by davcano** [microsoft-search/pnp-modern-search#3923]
**Version used**
v4.12.2

**Describe the bug**
When adding vertical web part on a page I have the error below. Notice that all the other Web Parts are working just fine:

ERREUR :
AADSTS65001: The user or administrator has not consented to use the application with ID '5f3e1536-0c84-4957-a6f9-869b63e81bb6' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource. Trace ID: c1375346-81b5-4db2-8ffb-cddf306a2f00 Correlation ID: cf72c74a-22f2-4b5b-ab1e-0aa89c6d0210 Timestamp: 2024-08-21 13:55:20Z

PILE DES APPELS :
InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID '5f3e1536-0c84-4957-a6f9-869b63e81bb6' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource. Trace ID: c1375346-81b5-4db2-8ffb-cddf306a2f00 Correlation ID: cf72c74a-22f2-4b5b-ab1e-0aa89c6d0210 Timestamp: 2024-08-21 13:55:20Z
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:6365)
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:44421)
    at new t (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:44840)
    at e.saveTokenFromHash (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:88271)
    at e.processCallBack (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:76518)
    at e.handleAuthenticationResponse (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:77833)
    at e.<anonymous> (https://res-1.cdn.office.net/files/sp-client/chunk.588_none_b1c3c5efff25e456c37d.js:2:72135)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_2636b7e9c725c3c8c7d42edbf2b1212a.js:1:11126
    at Object.next (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_2636b7e9c725c3c8c7d42edbf2b1212a.js:1:11231)
    at o (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_2636b7e9c725c3c8c7d42edbf2b1212a.js:1:9973)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to a page
2. Edit the page
3. Add the web part PnP - Verticaux de recherche
4. See the error

**Expected behavior**
I expect the Web Part to work

**Additional context**
I have the same issue with existing vertical web parts on other pages

**Comment by kasperbolarsen** [comment]
see https://github.com/microsoft-search/pnp-modern-search/issues/3879
It is a known issue, and a PR has already been committed. While waiting for the next release you could consider adding the User.Read permission

**Comment by davcano** [comment]
Hi, thanks for the reply. I will see with my admin can add the User.Read permission. Do you know when the next release will come?

**Comment by kasperbolarsen** [comment]
a preview is planned for next week, so perhaps in two weeks time if we don't discover any issue in the preview

**Comment by jblueml** [comment]
> Hi, thanks for the reply. I will see with my admin can add the User.Read permission. Do you know when the next release will come?

User.Read is not sufficient in that case. Please refer to [Group memberships for a user](https://learn.microsoft.com/en-us/graph/api/directoryobject-getmembergroups?view=graph-rest-1.0&tabs=http#group-memberships-for-a-user) to add necessary API permissions
