### ISSUE TITLE
Intermittent fault with Search Web Parts

### ISSUE THREAD

**Issue by elpinto007** [microsoft-search/pnp-modern-search#459]
!! Check existing issues before logging new ones !!

**Version used**
3.15

**Describe the bug**
When I click to get to the page of my SP site where I have added the webparts, I am getting the "Someone went wrong" message. The particular error message is "ae.a.getInstance(...).optOut is not a function".
TypeError: ae.a.getInstance(...).optOut is not a function
    at t.<anonymous> (https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:136876)
    at https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:134086
    at Object.next (https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:134191)
    at https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:133127
    at new Promise (<anonymous>)
    at le (https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:132904)
    at t.onInit (https://publiccdn.sharepointonline.com/company-name.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_2bf1cd834a7ee04c127c5f08f8d68aaf.js:1:136767)
    at t._onInViewport (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_f5c561960190f452faf4c9b74dab48b2.js:1:1820594)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_f5c561960190f452faf4c9b74dab48b2.js:1:1818599
    at new Promise (<anonymous>)

I don't think this is an issue with the web part itself, but it could be an issue with the configuration of my tenant. But I wanted to check if someone has come across something like this.

I searched the issues and found another issue with the same title, but the error message was different and was fixed by using the latest version. I am using the current (3.15) version. This issue also happened in the last version I had (released 5th August). 

The issue is intermittent, I can do a couple of refreshes and the web parts show up just fine.

**To Reproduce**
1. Deploy the latest package to your tenant.
2. Add webparts to a SharePoint page and configure search box, refiners and search results
3. Add navigation links to your SharePoint site
4. Click on navigation link

**Expected behavior**
The expected behaviour is when I click the navigation link, to see the search box presented on the SP page. 

**Screenshots**
![Annotation 2020-09-04 181655](https://user-images.githubusercontent.com/15204097/92293764-e033e500-eeda-11ea-87dd-44e4382c3d34.png)

**Desktop (please complete the following information):**
 - Browser - This issue is present in Chrome.

**Additional context**
From the error, it seems like an issue with how the web part is being loaded from the CDN. I am just wondering if there is any configuration that needs to change on my tenant. 
Thank you

**Comment by wobba** [comment]
Interesting and relates to opt out of PnP controls telemetry. I'll take a look and at least ensure we catch the exception. Will do a .1 release later for this.

**Comment by wobba** [comment]
Made a v3.15.1 release with this fix just now.
