### ISSUE TITLE
v4 - Can't insert or show webparts (Cannot read property 'DynamicPropertyDefinition' of undefined)

### ISSUE THREAD

**Issue by jreadwrite** [microsoft-search/pnp-modern-search#587]
**Version used**
v4.0.0.0

**Describe the bug**
On Edge or Chrome, when I change the browser language to German, the following error shows up on every pnp search webpart:

Da hat etwas nicht geklappt.
Wenn das Problem weiterhin besteht, wenden Sie sich an den Websiteadministrator, und teilen Sie ihm die Informationen unter "Technische Details" mit.

TECHNISCHE DETAILS
FEHLER: 
**Cannot read property 'DynamicPropertyDefinition' of undefined**
```

AUFRUFLISTE: 
_TypeError: Cannot read property 'DynamicPropertyDefinition' of undefined
    at t.getPropertyDefinitions (https://xyz.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_497fc978a57b44ee8e888b91deee5ae3.js:1:250486)
    at e._getPropertyDefinitions (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_6ba1b4897b4a1f9e94836d6770f5fa78.js:1:903767)
    at e._validateSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_6ba1b4897b4a1f9e94836d6770f5fa78.js:1:925724)
    at e.addSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_6ba1b4897b4a1f9e94836d6770f5fa78.js:1:924708)
    at e.initializeSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_6ba1b4897b4a1f9e94836d6770f5fa78.js:1:901761)
    at t.<anonymous> (https://xyz.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_497fc978a57b44ee8e888b91deee5ae3.js:1:245895)
    at https://xyz.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_497fc978a57b44ee8e888b91deee5ae3.js:1:244144
    at Object.next (https://xyz.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_497fc978a57b44ee8e888b91deee5ae3.js:1:244249)
    at s (https://xyz.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_497fc978a57b44ee8e888b91deee5ae3.js:1:242989)_

```
When I switch the browser language to English it works. The SharePoint default site language is English.

**To Reproduce**
1. Set browser language to de-de
2. Insert v4 PnP Search webpart

**Expected behavior**
PnP webparts should show up.

**Desktop (please complete the following information):**
 - Browser: tested on MS Edge and Google Chrome

**Comment by clublek** [comment]
I have more or less the same problem. When adding web parts under the user account which installed it in the Global App Catalog, everything goes fine.
Using my normal user account, i'm getting the following error when showing a publishing page or editing a page.

Cannot read property 'DynamicPropertyDefinition' of undefined

**Comment by FranckyC** [comment]
Hi @jreadwrite and @clublek , this will probably due to missing translations for German. Unlike v3, only English translations are implemented. I will see if we can do something about it to do not crash everything in this case. Thanks!

**Comment by FranckyC** [comment]
Found the issue and regenerate a new package https://github.com/microsoft-search/pnp-modern-search/releases/download/4.0.0-preview/pnp-modern-search-parts-v4.sppkg. Can you try it and tell me if the issue is resolved?

**Comment by jreadwrite** [comment]
Hi @FranckyC, looking good now - thanks for fixing the issue!
