### ISSUE TITLE
Unable to deploy PNP Modern Search V4 side by side with V3

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#605]
!! Check existing issues before logging new ones !!

**Version used**
3.16.0.0 and 4.0.0.0 

I have renamed V3 package to pnp-modern-search-parts-v3.sppkg and deployed it. Then I have uploaded V4 but when deploying, I have the following App Package Error message: Component ID {0} exists in solution {1} already.

![PnPSearchPackage](https://user-images.githubusercontent.com/11309224/101923533-81e36600-3b9d-11eb-804a-0c0c72fb20c9.png)

**Comment by wobba** [comment]
We're changing the package name for v4 to ensure you can deploy side by side. You can change it yourself and build as well until we get a new release out.

**Comment by coupalm** [comment]
Ok, I already renamed the V3 package name so I can upload both in catalog but you mean I need to change the title in the AppManifest of the V4 package? Can I activate both package on same site and decide to choose V3 or V4 web parts to insert in pages?

**Comment by FranckyC** [comment]
@coupalm I was able to reproduce your issue. You need to clear the client side components manifests from here for all Web Parts: `https://<your_site>/Lists/ComponentManifests/AllItem.aspx`.Then try to re-upload the v4 package. It should work

**Comment by coupalm** [comment]
Thanks @FranckyC , after cleaning the component manifests of the search web parts, I've reinstalled V4 successfully (and pnp-modern-search-extensibility.sppkg) and made the solution available to all sites. However, when I try to add the new web parts (v3 are working ok), I have errors. For instance, for the modern search result, I have the following: 

ERREUR :
Cannot read property 'WebPartDefaultTitle' of undefined

PILE DES APPELS :
TypeError: Cannot read property 'WebPartDefaultTitle' of undefined
    at t.getPropertyDefinitions (https://publiccdn.sharepointonline.com/unika.sharepoint.com/sites/AppsCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_30173b08ca7028c626c244b37bc6f531.js:1:206396)
    at e._getPropertyDefinitions (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr_1a7764316f86eb7ce054d9f90b342dec.js:1:910584)
    at e._validateSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr_1a7764316f86eb7ce054d9f90b342dec.js:1:932548)
    at e.addSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr_1a7764316f86eb7ce054d9f90b342dec.js:1:931532)
    at e.initializeSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr_1a7764316f86eb7ce054d9f90b342dec.js:1:908578)
    at t.<anonymous> (https://publiccdn.sharepointonline.com/unika.sharepoint.com/sites/AppsCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_30173b08ca7028c626c244b37bc6f531.js:1:211462)
    at https://publiccdn.sharepointonline.com/unika.sharepoint.com/sites/AppsCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_30173b08ca7028c626c244b37bc6f531.js:1:203980
    at Object.next (https://publiccdn.sharepointonline.com/unika.sharepoint.com/sites/AppsCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_30173b08ca7028c626c244b37bc6f531.js:1:204085)
    at a (https://publiccdn.sharepointonline.com/unika.sharepoint.com/sites/AppsCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_30173b08ca7028c626c244b37bc6f531.js:1:202825)

**Comment by FranckyC** [comment]
@coupalm By any chance, is your browser language other than english?

**Comment by FranckyC** [comment]
@coupalm Found the issue, I regenerated a new package for the release. Can you tell me if it works now?

**Comment by eldoro80** [comment]
> @coupalm Found the issue, I regenerated a new package for the release. Can you tell me if it works now?

I had the same issue. Works with the regenerated package. Thanks!

**Comment by coupalm** [comment]
Thanks, it's working.
