### ISSUE TITLE
Pnp-search webpart something went wrong - Cannot set property 'PagingID' of undefined

### ISSUE THREAD

**Issue by venkat061981** [microsoft-search/pnp-modern-search#660]
Hi,

We have implemented pnp-search webpart to in our SharePoint online. which was working fine in production environment. since morning it's stopped working and getting below error. Need experts help to resolve issue. Appreciate if you provide any resolution steps.

ERROR:
Cannot set property 'PagingID' of undefined
CALL STACK:
TypeError: Cannot set property 'PagingID' of undefined
at t.render (search-pagination-web-part_69e04f52bd02ec57ab84e3272180f9d2.js:80:450734)
at e.registerEvent (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:867792)
at e.add (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:869348)
at e.registerAvailableSourcesChanged (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:910100)
at t.onInit (https://tmcapartners.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-pagination-web-part_69e04f52bd02ec57ab84e3272180f9d2.js:80:452183)
at t._onInViewport (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:1699070)
at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:1697075
at new Promise (<anonymous>)
at t._internalFirstTimeRender (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:1696993)
at e._renderWebPart (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-au_e1ffb462db2cd4abd0fee45a848167a8.js:1:1727834)

**Comment by wobba** [comment]
Issue does not follow the issue template, missing versions and repro steps. Re-open once fixed or log a new issue.
