### ISSUE TITLE
The value for "id" must not be undefined

### ISSUE THREAD

**Issue by guptarajesh001** [microsoft-search/pnp-modern-search#688]
I have clone the pnp-modern-search solution from github, and deployed it on sharepoint online. When I am adding the Pnp-Search Results webpart on the Sharepoint online page. I am getting below error

ERROR:
The value for "id" must not be undefined

CALL STACK:
Error: The value for "id" must not be undefined
    at Function.e.isNotNullOrUndefined (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:850674)
    at e.tryGetSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:910863)
    at e.tryGetSource (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:925346)
    at SearchResultsWebPart.26CU.SearchResultsWebPart._bindHashChange (https://localhost:4321/dist/modern-search-results-web-part.js:12914:39)
    at SearchResultsWebPart.<anonymous> (https://localhost:4321/dist/modern-search-results-web-part.js:11684:30)
    at step (https://localhost:4321/dist/modern-search-results-web-part.js:11316:23)
    at Object.next (https://localhost:4321/dist/modern-search-results-web-part.js:11297:53)
    at fulfilled (https://localhost:4321/dist/modern-search-results-web-part.js:11288:58)

**Comment by wobba** [comment]
Closed as issue does not follow the guidelines in the bug template.
