### ISSUE TITLE
IE11 WebPart not loading

### ISSUE THREAD

**Issue by Mark-227** [microsoft-search/pnp-modern-search#937]
I know IE is not supported, but sadly we still need it in the company for some things. Of course everything works fine in Chrome, FireFox and Edge. We use PnP Modern Search V4.1 and everywhere the Web Part is implemented, the user gets the following error in IE11:

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/xyz.sharepoint.com/sites/app-katalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/search-parts-propertycontrolstrings_de-de_440a575b67a54069644382f11c4a9500.js' for resource 'PropertyControlStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/xyz.sharepoint.com/sites/app-katalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/search-parts-propertycontrolstrings_de-de_440a575b67a54069644382f11c4a9500.js' for resource 'PropertyControlStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:65:20220)
   at t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:65:19738)
   at t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:65:118757)
   at e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:65:156198)
   at e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:65:152237)
   at Anonymous function (https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_7a107ff8d813b6b18094.js:1:11885)
   at Anonymous function (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:1:8128)
   at R (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:1:8104)
   at C (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:1:7990)
   at T (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_971783ca27c61e1bcd9f77aebc0ac59a.js:1:7568)

I've found a solution to a similar problem of the V3 version, but the error was not the same and I was wondering if that could also work for the V4.1 https://github.com/SharePoint/sp-dev-docs/issues/6512

**Comment by wobba** [comment]
I tried to track down the issues but wasn't able to - and debugging in IE11 is too hard. If someone wants to give it a go, we will accept a PR to address it. So for now, too bad - and M365 will stop supporting IE11 in the fall anyways. Which means the customer really should think about moving to Edge - if not M365 might give them random errors going forward.

**Comment by Mark-227** [comment]
@wobba thank you for the time and effort, I really appreciate it.
